@'
medical_warehouse:
  target: dev
  outputs:
    dev:
      type: sqlite
      database: "../data/medical_warehouse.db"
      schema: main
      threads: 1
'@ | Out-File -FilePath "medical_warehouse\profiles.yml" -Encoding UTF8