@'
version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels with business classification"
    columns:
      - name: channel_key
        description: "Surrogate primary key for channel"
        tests:
          - unique
          - not_null
          
      - name: channel_name
        description: "Name of the Telegram channel"
        tests:
          - not_null
          
      - name: channel_type
        description: "Business classification (Pharmaceutical/Cosmetics/Medical/Other)"
        tests:
          - accepted_values:
              values: ['Pharmaceutical', 'Cosmetics', 'Medical', 'Other']
              
      - name: total_posts
        description: "Total number of posts from this channel"
        tests:
          - not_null

  - name: dim_dates
    description: "Date dimension for time-based analysis"
    columns:
      - name: date_key
        description: "Surrogate primary key (YYYYMMDD format)"
        tests:
          - unique
          - not_null
          
      - name: full_date
        description: "Calendar date"
        tests:
          - not_null
          
      - name: is_weekend
        description: "Flag indicating if date is weekend"
        tests:
          - accepted_values:
              values: [true, false]

  - name: fct_messages
    description: "Fact table containing Telegram messages with metrics"
    columns:
      - name: message_id
        description: "Original Telegram message ID"
        tests:
          - not_null
          
      - name: channel_key
        description: "Foreign key to dim_channels table"
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
              
      - name: date_key
        description: "Foreign key to dim_dates table"
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
              
      - name: view_count
        description: "Number of views on the message"
        tests:
          - not_null
          
      - name: has_image
        description: "Whether the message contains an image"
        tests:
          - accepted_values:
              values: [true, false]
'@ | Out-File -FilePath "medical_warehouse\models\marts\schema.yml" -Encoding UTF8