version: 2

sources:
  - name: raw
    schema: raw
    database: medical_warehouse
    tables:
      - name: telegram_messages
        description: "Raw Telegram messages scraped from medical channels"
        columns:
          - name: message_id
            description: "Unique message identifier from Telegram"
          - name: channel_name
            description: "Name of the Telegram channel"
          - name: message_date
            description: "Date and time when message was posted"
          - name: message_text
            description: "Text content of the message"
          - name: has_media
            description: "Whether message contains media"
          - name: image_path
            description: "Path to downloaded image (if applicable)"
          - name: views
            description: "Number of views on the message"
          - name: forwards
            description: "Number of times message was forwarded"
          - name: scraped_at
            description: "When the message was scraped"